In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
automobiles_data = pd.read_csv('datasets/CarPrice_Assignment.csv')

automobiles_data.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [3]:
automobiles_data.shape

(205, 26)

In [4]:
automobiles_data.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [5]:
automobiles_data.drop(['car_ID', 'symboling', 'CarName'], axis=1, inplace=True)

In [6]:
automobiles_data = pd.get_dummies(automobiles_data)

In [7]:
automobiles_data.head()

wheelbase  carlength  carwidth  carheight  curbweight  enginesize  \
0       88.6      168.8      64.1       48.8        2548         130   
1       88.6      168.8      64.1       48.8        2548         130   
2       94.5      171.2      65.5       52.4        2823         152   
3       99.8      176.6      66.2       54.3        2337         109   
4       99.4      176.6      66.4       54.3        2824         136   

   boreratio  stroke  compressionratio  horsepower  ...  \
0       3.47    2.68               9.0         111  ...   
1       3.47    2.68               9.0         111  ...   
2       2.68    3.47               9.0         154  ...   
3       3.19    3.40              10.0         102  ...   
4       3.19    3.40               8.0         115  ...   

   cylindernumber_twelve  cylindernumber_two  fuelsystem_1bbl  \
0                      0                   0                0   
1                      0                   0                0   
2                      0                   0                0   
3                      0                   0                0   
4                      0                   0                0   

   fuelsystem_2bbl  fuelsystem_4bbl  fuelsystem_idi  fuelsystem_mfi  \
0                0                0               0               0   
1                0                0               0               0   
2                0                0               0               0   
3                0                0               0               0   
4                0                0               0               0   

   fuelsystem_mpfi  fuelsystem_spdi  fuelsystem_spfi  
0                1                0                0  
1                1                0                0  
2                1                0                0  
3                1                0                0  
4                1                0                0  

[5 rows x 52 columns]

In [8]:
automobiles_data.shape

(205, 52)

In [9]:
X = automobiles_data.drop('price', axis=1)

Y = automobiles_data['price']

In [10]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [11]:
x_train.shape, x_test.shape

((164, 51), (41, 51))

In [12]:
y_train.shape, y_test.shape

((164,), (41,))

In [13]:
model = LinearRegression().fit(x_train, y_train)

In [14]:
Training_score = model.score(x_train, y_train)

Training_score

0.9440854244581013

In [15]:
y_pred = model.predict(x_test)

y_pred

array([ 7444.89186293,  6107.84797371,  6049.18256523, 19825.94708797,
       32528.        , 30807.41618538,  8692.87625137,  9125.72096319,
        7207.11434219, 19170.8276747 ,  6188.51470274,  9401.00847633,
        5813.54598939,  6262.64324424, 10306.13737638,  6813.36604948,
       20592.97413267, 14009.47828664, 16739.305685  , 36231.72683087,
       19375.49338246, 12255.15918087,  4645.90907822,  2907.80679854,
       21891.51077272,  8279.80182408, 20407.83457986,  7744.62861042,
        6867.37449214, 15339.94905903, 26981.58814282,  7330.23962357,
       10847.34713738, 10580.29395604, 11204.29548865, 16854.12140335,
       12289.53597444,  8111.82608409,  8791.33624935,  5652.69148029,
        6225.66047874])

In [16]:
Testing_score = r2_score(y_test, y_pred)

Testing_score

0.8959668832301437

In [17]:
import json

In [18]:
model.coef_

array([ 1.15436036e+02, -7.64558532e+01,  7.98267776e+02, -8.09776994e+01,
        2.18561022e+00,  1.10389625e+02,  5.24354498e+02, -5.58396271e+03,
       -8.39249376e+02,  2.44762579e+01,  2.16130293e+00, -2.04559230e+02,
        1.85296646e+02,  4.79050797e+03, -4.79050797e+03, -6.68068291e+02,
        6.68068291e+02, -1.28586442e+02,  1.28586442e+02,  2.70206002e+03,
       -9.05499959e+02, -1.27327912e+03, -9.75163929e+01, -4.25764550e+02,
       -2.79987982e+01,  4.64655065e+01, -1.84667083e+01, -2.92036001e+03,
        2.92036001e+03,  1.85298888e+03, -9.96169739e+03,  1.53684541e+03,
        5.98842510e+03,  2.23087313e+03, -4.85622058e+03,  3.20878544e+03,
        7.07037415e+03, -4.69993301e+03, -5.58307779e+03, -7.25670107e+02,
        5.25745256e+03, -4.52793125e+03,  3.20878544e+03,  1.01826994e+03,
        5.45802381e+02, -9.50683406e+02,  4.79050797e+03, -3.52504029e+03,
        1.85914647e+00, -2.64804402e+03,  7.67328273e+02])

In [19]:
model.intercept_

-34979.589262877074

In [20]:
model_param = {}

model_param['coef'] = list(model.coef_)
model_param['intercept'] = model.intercept_.tolist()

In [21]:
json_txt = json.dumps(model_param, indent=4)

json_txt

'{\n    "coef": [\n        115.43603644064791,\n        -76.45585322665004,\n        798.2677762741353,\n        -80.97769937242035,\n        2.1856102227330894,\n        110.38962474709689,\n        524.3544976358448,\n        -5583.962712123348,\n        -839.2493755716412,\n        24.476257886627536,\n        2.1613029280829323,\n        -204.5592304501008,\n        185.29664567960435,\n        4790.5079717625595,\n        -4790.50797176252,\n        -668.0682908967809,\n        668.0682908967739,\n        -128.58644173311683,\n        128.5864417332345,\n        2702.060021680085,\n        -905.4999593944599,\n        -1273.2791191900342,\n        -97.51639291514948,\n        -425.76455018033516,\n        -27.998798202527936,\n        46.465506531404,\n        -18.46670832892937,\n        -2920.3600145788732,\n        2920.3600145788646,\n        1852.9888805517546,\n        -9961.697385031603,\n        1536.8454089875138,\n        5988.425100763828,\n        2230.87313023632,\n  

In [22]:
with open('models/regressor_param.txt', 'w') as file:
    
    file.write(json_txt)

In [23]:
with open('models/regressor_param.txt', 'r') as file:
    
    json_text=json.load(file)

In [24]:
json_model = LinearRegression()

In [25]:
json_model.coef_ = np.array(json_text['coef'])
json_model.intercept_ = np.array(json_text['intercept'])

In [26]:
y_pred = json_model.predict(x_test)

r2_score(y_test, y_pred)

0.8959668832301437

In [27]:
Testing_score

0.8959668832301437

In [28]:
import pickle

In [29]:
pickle.dump(model, open('models/model.pkl', 'wb'))

In [30]:
pickle_model = pickle.load(open('models/model.pkl', 'rb'))

In [31]:
y_pred = pickle_model.predict(x_test)

y_pred

array([ 7444.89186293,  6107.84797371,  6049.18256523, 19825.94708797,
       32528.        , 30807.41618538,  8692.87625137,  9125.72096319,
        7207.11434219, 19170.8276747 ,  6188.51470274,  9401.00847633,
        5813.54598939,  6262.64324424, 10306.13737638,  6813.36604948,
       20592.97413267, 14009.47828664, 16739.305685  , 36231.72683087,
       19375.49338246, 12255.15918087,  4645.90907822,  2907.80679854,
       21891.51077272,  8279.80182408, 20407.83457986,  7744.62861042,
        6867.37449214, 15339.94905903, 26981.58814282,  7330.23962357,
       10847.34713738, 10580.29395604, 11204.29548865, 16854.12140335,
       12289.53597444,  8111.82608409,  8791.33624935,  5652.69148029,
        6225.66047874])

In [32]:
r2_score(y_test, y_pred)

0.8959668832301437

In [33]:
Testing_score

0.8959668832301437

In [34]:
import joblib

In [35]:
filename = 'models/model.joblib'

In [36]:
joblib.dump(model, filename)

['models/model.joblib']

In [37]:
joblib_model = joblib.load(filename)

In [38]:
y_pred = joblib_model.predict(x_test)

y_pred

array([ 7444.89186293,  6107.84797371,  6049.18256523, 19825.94708797,
       32528.        , 30807.41618538,  8692.87625137,  9125.72096319,
        7207.11434219, 19170.8276747 ,  6188.51470274,  9401.00847633,
        5813.54598939,  6262.64324424, 10306.13737638,  6813.36604948,
       20592.97413267, 14009.47828664, 16739.305685  , 36231.72683087,
       19375.49338246, 12255.15918087,  4645.90907822,  2907.80679854,
       21891.51077272,  8279.80182408, 20407.83457986,  7744.62861042,
        6867.37449214, 15339.94905903, 26981.58814282,  7330.23962357,
       10847.34713738, 10580.29395604, 11204.29548865, 16854.12140335,
       12289.53597444,  8111.82608409,  8791.33624935,  5652.69148029,
        6225.66047874])

In [39]:
r2_score(y_test, y_pred)

0.8959668832301437

In [40]:
Testing_score

0.8959668832301437